/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package syndeo_jms_comms;

import java.io.*;
import java.text.*;
import javax.xml.transform.stream.StreamSource;
import org.apache.ws.commons.schema.*;

import javax.jms.*;
import javax.xml.bind.*;
import org.apache.activemq.ActiveMQConnectionFactory;
import org.apache.activemq.command.*;


public class App {

    private static ConnectionFactory factory = null;
    private static Connection con = null;
    private static Session session = null;
    private static Queue inbox_queue = null;
    private static Queue out_queue = null;

    private static MessageProducer producer = null;

    public static void main(String[] args) throws Exception {
        run_test();
    }

    public static void on_exit() {
        unsafe(() -> {
          session.close();
        });
        unsafe(() -> {
          con.close();
        });
    }

    public static void run_test() throws Exception {

        Runtime.getRuntime().addShutdownHook(new Thread(App::on_exit));

        // Currently this talks to some unknown host and listens to JMS messages
        String conn_url = System.getenv("SYNDEO_JMS_URL");
        System.err.println("syndeo setup conn_url="+conn_url);

        // Start thread to tx message every 10 seconds
        //new Thread(App::test_tx).start();

        factory = new ActiveMQConnectionFactory(
            System.getenv("SYNDEO_JMS_USER"),
            System.getenv("SYNDEO_JMS_PASS"),
            conn_url
        );

        Connection con = factory.createConnection();
        con.start();
        
        //session = con.createSession(false, Session.AUTO_ACKNOWLEDGE);
        session = con.createSession(false, Session.CLIENT_ACKNOWLEDGE); // we must call Message::acknowledge() to ack a message
        inbox_queue = session.createQueue( "dt_receive" );

        MessageConsumer consumer = session.createConsumer(inbox_queue);
        consumer.setMessageListener(new SyndeoListener());
        
        out_queue = session.createQueue( "dt_send" );
        System.err.println("out_queue="+out_queue);

        producer = session.createProducer(out_queue);
        producer.setDeliveryMode(DeliveryMode.PERSISTENT);

        unsafe(() -> {
          Thread.sleep(99999 * 1000);
        });
    }

    public static void test_tx() {
        while(true) {
          unsafe(() -> { Thread.sleep(10 * 1000); });

          System.out.println("test_tx");
          
          unsafe(() -> {
          
            com.brandes.syndeo.mil_std_2045_47001.Message outgoing_msg = new com.brandes.syndeo.mil_std_2045_47001.Message();

            outgoing_msg.setMessageId(java.util.UUID.randomUUID().toString());
            outgoing_msg.setMessageType(com.brandes.syndeo.mil_std_2045_47001.MessageTypeType.TEXT);
            outgoing_msg.setMessageSubType("");
            outgoing_msg.setCompression(com.brandes.syndeo.mil_std_2045_47001.CompressionType.NONE);

            outgoing_msg.setSubject("Test subject 001");
            outgoing_msg.setFrom("DEVILTECH USER1");

            DateFormat dateFormat = new SimpleDateFormat("ddHHmm'Z' MMM yy"); // 201617Z APR 20
            outgoing_msg.setDTG(dateFormat.format(new java.util.Date()).toUpperCase());

            outgoing_msg.setPrecedenceTo("ROUTINE");
            outgoing_msg.setPrecedenceCopy("ROUTINE");
            outgoing_msg.setClassification(com.brandes.syndeo.mil_std_2045_47001.ClassificationType.UNCLASSIFIED);
            
            com.brandes.syndeo.mil_std_2045_47001.RecipientsType recipients = new com.brandes.syndeo.mil_std_2045_47001.RecipientsType();
            recipients.getRecipient().add("Recipient 001");
            outgoing_msg.setRecipientsTo(recipients);
            
            com.brandes.syndeo.mil_std_2045_47001.RecipientsType recipients_copy = new com.brandes.syndeo.mil_std_2045_47001.RecipientsType();
            outgoing_msg.setRecipientsCopy(recipients_copy);
            
            String subj = "Subject line 001";
            String body_str = "Text body message 001";
            body_str = "SUBJ: "+subj+"&#xD;\n"+body_str;

            outgoing_msg.setBody(body_str);

            JAXBContext jaxbContext = JAXBContext.newInstance(com.brandes.syndeo.mil_std_2045_47001.Message.class);
            Marshaller jaxbMarshaller = jaxbContext.createMarshaller();
            //jaxbMarshaller.setProperty(Marshaller.JAXB_FORMATTED_OUTPUT, Boolean.TRUE); // To format XML with whitespace
            jaxbMarshaller.setProperty(Marshaller.JAXB_FORMATTED_OUTPUT, Boolean.FALSE); // To format XML w/o spaces
            // This prefix mapper simply prefixes everything with "devil"
            jaxbMarshaller.setProperty("com.sun.xml.bind.namespacePrefixMapper", new com.sun.xml.bind.marshaller.NamespacePrefixMapper() {
                    @Override
                    public String getPreferredPrefix(String namespaceUri, String suggestion, boolean requirePrefix) {
                        //System.err.println("getPreferredPrefix("+namespaceUri+", "+suggestion+", "+requirePrefix+")");
                        return "devil";
                    }
            });
            // This removes the first line of output, <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
            jaxbMarshaller.setProperty("com.sun.xml.bind.xmlDeclaration", Boolean.FALSE);

            StringWriter xml_out = new StringWriter();
            jaxbMarshaller.marshal(outgoing_msg, xml_out);

            String xml_text = xml_out.toString();
            System.err.println("Syndeo plugin is sending xml_text="+xml_text);

            TextMessage message = session.createTextMessage(xml_text);

            org.apache.activemq.ActiveMQMessageProducer apache_p = (org.apache.activemq.ActiveMQMessageProducer) producer;
            apache_p.send(message, new org.apache.activemq.AsyncCallback() {
                public void onException(javax.jms.JMSException exception)  {
                    System.err.println("onException("+exception+")");
                }
                public void onSuccess()  {
                    System.err.println("onSuccess()");
                }
            });
          });
        }
    }


    @FunctionalInterface
    public static interface UnsafeRunnable {
        public void run() throws Throwable;
    }

    private static void unsafe(UnsafeRunnable r) {
        try {
          r.run();
        }
        catch (Throwable t) {
          t.printStackTrace();
        }
    }

    private static class SyndeoListener implements MessageListener {
        public void onMessage(javax.jms.Message message_iface) {
            unsafe(() -> {
              // TODO parse and forward to other plugins
              // See https://docs.oracle.com/javaee/7/api/javax/jms/Message.html
              if (message_iface instanceof ActiveMQTextMessage) {
                  ActiveMQTextMessage message = (ActiveMQTextMessage) message_iface;

                  this.withXmlString(message.getText(), () -> {
                      unsafe(() -> { message.acknowledge(); });
                  });

                  // We acknowledge messages after 3 minutes to allow multiple locorum instances to receive them;
                  new Thread(() -> {
                      unsafe(() -> { Thread.sleep(3 * 60 * 1000); });
                      unsafe(() -> { message.acknowledge(); });
                  }).start();

              }
              else {
                  System.err.println("message not instance of ActiveMQTextMessage");
                  throw new RuntimeException("message not instance of ActiveMQTextMessage");
              }
            });
        }
        public void withXmlString(String msg_xml, Runnable to_ack) {
            unsafe(() -> {
              System.err.println("\nmsg_xml="+msg_xml+"\n");
              JAXBContext jaxbContext = JAXBContext.newInstance(com.brandes.syndeo.mil_std_2045_47001.Message.class);
              Unmarshaller u = jaxbContext.createUnmarshaller();
              Object o = u.unmarshal(new StringReader(msg_xml));
              if (o instanceof com.brandes.syndeo.mil_std_2045_47001.Message) {
                  com.brandes.syndeo.mil_std_2045_47001.Message m = (com.brandes.syndeo.mil_std_2045_47001.Message) o;
                  this.withMessage(m, to_ack);
              }
              else {
                  throw new RuntimeException("SyndeoListener::withXmlString o = "+o);
              }
            });
        }
        public void withMessage(com.brandes.syndeo.mil_std_2045_47001.Message m, Runnable to_ack) {
            // Call to_ack to acknowledge this message after it has been parsed and we can check recipients
            // SimpleDateFormat syndeo_dtg_fmt = new SimpleDateFormat("ddHHmm'Z' MMM yy");
            // SimpleDateFormat fmt = new SimpleDateFormat("yyyy-MM-dd HH:mm");

            // java.util.Date msg_dtg = (java.util.Date) syndeo_dtg_fmt.parseObject(m.getDTG());

            System.err.println("rx m = "+m);

            to_ack.run();

        }
    }


}
